// Pixel-art icon lookup, generated by tools/gen_icons.py into assets/icons/.
// Mirrors assets.js's tryLoadImage poll pattern (no callbacks/promises).
import { tryLoadImage } from './assets.js';

export function getIconImg(id) {
  if (!id) return null;
  return tryLoadImage(`assets/icons/${id}.png`);
}

// Returns an <img> tag that falls back to the emoji text if the icon PNG
// is missing or fails to load, so unmapped ids degrade gracefully.
export function iconTag(id, fallbackEmoji, cls = 'icon-img') {
  const safeFallback = (fallbackEmoji || '').replace(/'/g, '&#39;');
  return `<img class="${cls}" src="assets/icons/${id}.png" alt="" `
    + `onerror="this.outerHTML='<span class=&quot;${cls}-fallback&quot;>${safeFallback}</span>'">`;
}
